name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Lint • Typecheck • Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        env:
          CI: true
        run: npm run test:unit

  build:
    name: Production build (main only)
    runs-on: ubuntu-latest
    needs: verify
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          NUXT_TELEMETRY_DISABLED: 1
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run build

      # Optional: only upload artifacts on failure (saves time/storage)
      - name: Upload build output (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: nuxt-output
          path: .output
          if-no-files-found: ignore